---
collections:
  - name: ansible.windows
    version: 2.3.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.1.0
  - name: community.general
    version: 8.4.0
  - name: community.windows
    version: 2.2.0
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: microsoft.ad
    version: 1.5.0

roles:
  - name: lae.proxmox
    version: v1.8.0
  - name: geerlingguy.packer
    version: 1.0.2
  - name: ansible-thoteam.nexus3-oss
    version: v2.5.2
  - name: gantsign.golang
    version: 3.3.1
